[package]
name = "resolve"
version = "0.1.0"
authors = ["Zaid <startswithzed@gmail.com>"]
edition = "2021"

[dependencies]
rand = "0.6"
clap = "2.33"
trust-dns = { version = "0.16", default-features = false }

