[package]
name = "clock"
version = "0.1.2"
authors = ["Zaid <startswithzed@gmail.com>"]
edition = "2021"

[dependencies]
chrono = "0.4"
clap = "2"
byteorder = "1.2"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2"
winapi = "0.2"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"
